server:
  port: 8094

spring:
  application:
    name: merchant-service

  datasource:
    url: jdbc:mysql://localhost:3308/merchant_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true